# Generated by Django 3.1 on 2020-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(default='Software Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='shortDescription',
            field=models.TextField(default='This is a description but shorter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Here comes some technologies', max_length=100),
            preserve_default=False,
        ),
    ]
